version: '2'
# Simple single server setup for prod

services:
  app:
    environment:
     - SYMFONY_HTTP_CACHE=0
     - SYMFONY_TRUSTED_PROXIES=varnish
# @todo Add env variable taken into account by eZ Platform for configuring varnish purging

  varnish:
    image: kardasz/varnish
    ports:
     - "8081:80"
    depends_on:
     - web
    volumes:
     - ${COMPOSE_DIR}/entrypoint/varnish/varnish4.vcl:/etc/varnish/default.vcl:ro
